export const foodsData = [
  {
    id: 5,
    label: "پاستا چیکن آلفردو",
    category: "pasta",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pasta.webp",
  },
  {
    id: 6,
    label: "پاستا چیکن آلفردو",
    category: "pasta",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pasta.webp",
  },
  {
    id: 7,
    label: "پاستا چیکن آلفردو",
    category: "pasta",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pasta.webp",
  },
  {
    id: 8,
    label: "پاستا چیکن آلفردو",
    category: "pasta",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pasta.webp",
  },
  {
    id: 9,
    label: "پیتزا پپرونی ایتالیایی",
    category: "pizza",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pizza.webp",
  },
  {
    id: 10,
    label: "پیتزا پپرونی ایتالیایی",
    category: "pizza",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pizza.webp",
  },
  {
    id: 11,
    label: "پیتزا پپرونی ایتالیایی",
    category: "pizza",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pizza.webp",
  },
  {
    id: 12,
    label: "پیتزا پپرونی ایتالیایی",
    category: "pizza",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/pizza.webp",
  },
  {
    id: 13,
    label: "سالاد سزار",
    category: "appetizer",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/salad.webp",
  },
  {
    id: 14,
    label: "سالاد سزار",
    category: "appetizer",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/salad.webp",
  },
  {
    id: 15,
    label: "سالاد سزار",
    category: "appetizer",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/salad.webp",
  },
  {
    id: 16,
    label: "سالاد سزار",
    category: "appetizer",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/salad.webp",
  },
  {
    id: 1,
    label: "چیز برگر",
    category: "burger",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/burger.webp",
  },
  {
    id: 2,
    label: "چیز برگر",
    category: "burger",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/burger.webp",
  },
  {
    id: 3,
    label: "چیز برگر",
    category: "burger",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/burger.webp",
  },
  {
    id: 4,
    label: "چیز برگر",
    category: "burger",
    description: "پاستا، سینه مرغ، سبزیجات معطر، سس مخصوص و...",
    price: "125,000 تومان",
    img: "/images/burger.webp",
  },
];
